### PR TITLE
API behaves badly with 'null' bodies

### PR DESCRIPTION
**Pull request by ruilapa**
"data" should not be sent if there's not a body.

### CODE REVIEW

**Comment by ruilapa** [comment]
An error happens in the API in a multipage request... like:
import linode
client = linode.LinodeClient('API_KEY')

**Comment by ruilapa** [comment]
A error occurs on the API in multipage requests.
Example:
import linode
client = linode.LinodeClient('API_KEY')
for instance in client.linode.get_instances():
    print instance
    for ipv4 in instance.ipv4:
        print ipv4

**Comment by Dorthu** [comment]
I could not reproduce this, what am I doing wrong?

What I did using python2 and linode-api-4.1.7b0:

```python
>>> import linode
>>> lc = linode.LinodeClient(token)
>>> for instance in lc.linode.get_instances():
...   print instance
...   for ipv4 in instance.ipv4:
...     print ipv4
```

Could you please include the error/stacktrace you're getting to help me reproduce this issue?

**Comment by Dorthu** [comment]
I did some debugging and determined this is an issue on our end - although passing `'null'` as the request body on a GET is probably not a good call either.  I've added this to our internal bug tracker and will update you when a fix is deployed.  I'm going to hold off on accepting this PR until then to confirm that the issue is fixed on our end first.

**Comment by RobertDeRose** [comment]
This should be fixed now @ruilapa. If you could let us know if it's resolved, that would be great!

**Comment by anigeo** [comment]
Looks like this affected today, all get requests broken now.

```
c.linode.get_instances()
---------------------------------------------------------------------------
ApiError                                  Traceback (most recent call last)
<ipython-input-6-45391b5315a8> in <module>()
----> 1 c.linode.get_instances()

~/Codes/linode_v4/linode-env/lib/python3.6/site-packages/linode/linode_client.py in get_instances(self, *filters)
     29
     30     def get_instances(self, *filters):
---> 31         return self.client._get_and_filter(Linode, *filters)
     32
     33     def get_stackscripts(self, *filters, **kwargs):

~/Codes/linode_v4/linode-env/lib/python3.6/site-packages/linode/linode_client.py in _get_and_filter(self, obj_type, *filters)
    654                 parsed_filters = filters[0].dct
    655
--> 656         return self._get_objects(obj_type.api_list(), obj_type, filters=parsed_filters)

~/Codes/linode_v4/linode-env/lib/python3.6/site-packages/linode/linode_client.py in _get_objects(self, endpoint, cls, model, parent_id, filters)
    485
    486     def _get_objects(self, endpoint, cls, model=None, parent_id=None, filters=None):
--> 487         response_json = self.get(endpoint, model=model, filters=filters)
    488
    489         if not "data" in response_json:

~/Codes/linode_v4/linode-env/lib/python3.6/site-packages/linode/linode_client.py in get(self, *args, **kwargs)
    501
    502     def get(self, *args, **kwargs):
--> 503         return self._api_call(*args, method=requests.get, **kwargs)
    504
    505     def post(self, *args, **kwargs):

~/Codes/linode_v4/linode-env/lib/python3.6/site-packages/linode/linode_client.py in _api_call(self, endpoint, model, method, data, filters)
    475             except:
    476                 pass
--> 477             raise ApiError(error_msg, status=response.status_code, json=j)
    478
    479         if response.status_code != 204:

ApiError: 400: Invalid JSON;
```

**Comment by ruilapa** [comment]
Can someone please merge this and release a new version.
This is a double safeguard for the API "null", which is barking again.

**Comment by Dorthu** [comment]
This has been fixed in `v4.1.8b1` in https://github.com/linode/python-linode-api/commit/a759821b769e16b3151a3f6d1ca6a98302529baa - sorry for the inconvenience

**Comment by ruilapa** [comment]
Perfect Thanks

**Pull request closed without merging**
